### ISSUE TITLE
Bundle project with sbt 0.13.7 produces logging error 

### ISSUE THREAD

**Issue by dsugden** [sbt/sbt-conductr#76]
Steps to reproduce:

cd into sbt-conductr-tester sub project

changes build.properties to:

    sbt.version = 0.13.7

try to load a bundle to a conductr server:

    java.lang.RuntimeException: Settings logger used after project was loaded.
	at scala.sys.package$.error(package.scala:27)
	at sbt.LogManager$$anon$1$$anonfun$slog$1.apply(LogManager.scala:110)
	at sbt.LogManager$$anon$1$$anonfun$slog$1.apply(LogManager.scala:110)
	at scala.Option.getOrElse(Option.scala:120)
	at sbt.LogManager$$anon$1.slog(LogManager.scala:110)
	at sbt.LogManager$$anon$1.log(LogManager.scala:115)
	at sbt.Logger$class.info(Logger.scala:117)
	at sbt.LogManager$$anon$1.info(LogManager.scala:108)
	at com.typesafe.conductr.sbt.ConductR$$anonfun$com$typesafe$conductr$sbt$ConductR$$doLoadBundle$1$1.apply(ConductR.scala:39)
	at com.typesafe.conductr.sbt.ConductR$$anonfun$com$typesafe$conductr$sbt$ConductR$$doLoadBundle$1$1.apply(ConductR.scala:38)

This is due to using sLog as the logger. It looks like Josh fixed this in 0.13.8

However:  wouldn't it be better to just use 

    state.log.info("yadda")

instead of passing this logger through?

I've tested this and it works. I can create a PR tomorrow 9AM (-4 UTC)

**Comment by huntc** [comment]
Yes, better to use `state`. PR appreciated. Thanks.

**Comment by huntc** [comment]
Fixed PR https://github.com/sbt/sbt-conductr/pull/78

**Comment by cppexpert** [comment]
I get this error in 0.13.8

```
java.lang.RuntimeException: Settings logger used after project was loaded.
        at scala.sys.package$.error(package.scala:27)
        at sbt.LogManager$$anon$1$$anonfun$slog$1.apply(LogManager.scala:110)
        at sbt.LogManager$$anon$1$$anonfun$slog$1.apply(LogManager.scala:110)
        at scala.Option.getOrElse(Option.scala:120)
        at sbt.LogManager$$anon$1.slog(LogManager.scala:110)
        at sbt.LogManager$$anon$1.log(LogManager.scala:115)
        at sbt.Logger$class.info(Logger.scala:118)
        at sbt.LogManager$$anon$1.info(LogManager.scala:108)
        at bintray.BintrayRepo.release(BintrayRepo.scala:73)
        at bintray.BintrayPlugin$$anonfun$bintrayPublishSettings$16.apply(BintrayPlugin.scala:117)
        at bintray.BintrayPlugin$$anonfun$bintrayPublishSettings$16.apply(BintrayPlugin.scala:114)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:bintrayRelease) Settings logger used after project was loaded.
```

Any suggestions ?
